sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CI_ROS_DISTRO="indigo"
#  matrix:
#    - CI_ROS_DISTRO="indigo"
#    - CI_ROS_DISTRO="jade"
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python3 python3.4-dev python3-numpy libblas-dev liblapack-dev gfortran python3-scipy
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update
  - sudo apt-get install ros-indigo-desktop
  - sudo apt-get install flex freeglut3-dev
  - sudo apt-get install mongodb
  - sudo apt-get install python3-catkin-tools python3-catkin-pkg
  # Use rosdep to install all dependencies (including ROS itself)
script:
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir -p $CATKIN_WS_SRC
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
  - cd $CATKIN_WS
  - git clone git@github.com:squirrel-project/squirrel_common.git ~/catkin_ws/src/squirrel_common
  - git clone git@github.com:clearpathrobotics/occupancy_grid_utils.git ~/catkin_ws/src/occupancy_grid_utils
  - git clone git@github.com:kcl-planning/ROSPlan.git ~/catkin_ws/src/ROSPlan
  - catkin init
  - rosdep install --from-paths src/ -i -y --rosdistro $CI_ROS_DISTRO
  # Enable install space
  #- catkin config --install
  # Build [and Install] packages
  - catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
  # Build tests
  - catkin build --limit-status-rate 0.1 --no-notify --make-args tests
  # Run tests
  #- catkin run_tests
